# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fridgeApp', '0005_auto_20161127_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 27, 19, 32, 38, 287971, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
