# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridgeApp', '0006_auto_20161127_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cook_information',
            old_name='time',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='cook_information',
            old_name='time_unit',
            new_name='value_unit',
        ),
    ]
