# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridgeApp', '0007_auto_20161128_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions_text', models.CharField(max_length=1500)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridgeApp.Recipe')),
            ],
        ),
    ]
